version: 0.2

phases:
  install:
    commands:
      - echo "Before install:"
      - echo $(java -version)
      - echo "After install:"
      - echo $(java -version)
  pre_build:
    commands:
      - echo "We are in the pre build phase"
  build:
    commands:
      - echo "We are in the build phase"
      - mvn -Dmaven.test.skip package
  post_build:
    commands:
      - echo "We are in the post build phase"