version: '3.8'
services:
  ap-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    hostname: ap-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./ap-es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    stop_grace_period: 5m
  search:
    profiles:
      - main
    build:
      context: .
      dockerfile: ./search/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ap-es
  frontend:
    profiles:
      - main
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - search
  ingest:
    profiles:
      - ingest
    build:
      context: .
      dockerfile: ./ingest/Dockerfile
    volumes:
      - ./ingest/pharmacy.csv:/app/csv/pharmacy.csv
    ports:
      - "8081:8080"
    depends_on:
      - ap-es
